### ISSUE TITLE
Potential vulnerabilities in Puppet files: Hard-coded Secret

### ISSUE THREAD

**Issue by cantebigene** [asottile/personal-puppet#18]
18 hard-coded secrets were found in 11 different scripts.

Script 1: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/util/manifests/pip.pp
 - Line [5](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/util/manifests/pip.pp#L5): `user=asottile`

Script 2: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/util/manifests/virtualenv.pp
 - Line [14](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/util/manifests/virtualenv.pp#L14): `user=asottile`

Script 3: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/workspace.pp
 - Line [18](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/workspace.pp#L18): `user=asottile`
 - Line [26](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/workspace.pp#L26): `user=asottile`
 - Line [41](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/workspace.pp#L41): `user=asottile`
 - Line [55](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/workspace.pp#L55): `user=asottile`

Script 4: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/screensaver.pp
 - Line [4](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/screensaver.pp#L4): `user=asottile`
 - Line [8](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/screensaver.pp#L8): `user=asottile`

Script 5: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/background.pp
 - Line [7](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/background.pp#L7): `user=asottile`
 - Line [11](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/background.pp#L11): `user=asottile`

Script 6: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/pypy.pp
 - Line [17](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/pypy.pp#L17): `user=asottile`
 - Line [42](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/pypy.pp#L42): `user=asottile`

Script 7: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/terraform.pp
 - Line [21](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/terraform.pp#L21): `user=asottile`

Script 8: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/go.pp
 - Line [19](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/go.pp#L19): `user=asottile`

Script 9: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/packer.pp
 - Line [21](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/packer.pp#L21): `user=asottile`

Script 10: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/dotfiles.pp
 - Line [14](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/dotfiles.pp#L14): `user=asottile`

Script 11: https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/launcher.pp
 - Line [10](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/launcher.pp#L10): `user=asottile`
 - Line [15](https://github.com/asottile/personal-puppet/blob/b916fdbf4f0d0213ac2dab66a9ca71e0f068a782/modules/desktop/manifests/launcher.pp#L15): `user=asottile`

A secret can be a password, user name, or private cryptographic key. 

This type of smell can lead to well-known types of vulnerabilities, as documented by CWE ([CWE-798](https://cwe.mitre.org/data/definitions/798.html) and [CWE-259](https://cwe.mitre.org/data/definitions/259.html)). Hard-coded secrets can be used to bypass protection mechanisms, gain privileges on applications and access to sensitive data. 

Storing secrets in **Puppet** configuration files is considered to be a security smell (cf. [[icse19](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
To protect/manage your secrets, it is recommended to use a vault (e.g., [https://www.vaultproject.io/](https://www.vaultproject.io/)). After configuring the vault, you can replace your secrets by variables from the vault. For instance, replace`$password = ‘12345’` by `$password = $vault::password`. Thus, your secrets will no longer be disclosed publicly.

**Comment by asottile** [comment]
fuck off
